

services:
  frontend:
    build: ./frontend/voting-app
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=mariadb
      - DATABASE_USER=root
      - DATABASE_PASSWORD=example
      - DATABASE_NAME=voting_app
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=voting_app
    ports:
      - "3306:3306"

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - mariadb